pipeline:
  name: remote
  identifier: remote
  projectIdentifier: DoNotDelete_AR7
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: h
        identifier: h
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
