pipeline:
  name: remote_pipe_infra_multi_svc_bug
  identifier: remote_pipe_infra_multi_svc_bug
  projectIdentifier: DoNotDelete_AR7
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: multi_svc_infra_bug
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              environments:
                values:
                  - environmentRef: test_env_ar7_bug
                    infrastructureDefinitions:
                      - identifier: infra
